### ISSUE TITLE
Error in IPA file path inside semaphore.yml configuration

### ISSUE THREAD

**Issue by amarildolucas** [semaphoreci-demos/semaphore-demo-ios-swift-xcode#6]
The line `output_directory('build')` inside `fastlane/Gymfile` creates a `build` directory in project root folder with the `TallestTowers.ipa` file, but in the `semaphore.yml` configuration to upload the IPA file as a job artifact we have `artifact push job TallestTowers.ipa`, the Build job finish with an error related to not finding the IPA file. 

It probably should be `artifact push job build/TallestTowers.ipa`.

**Comment by markoa** [comment]
OK, please submit a PR with the correct command as you work on the article.
