### ISSUE TITLE
Inconsistencies in the docs vs the demo project

### ISSUE THREAD

**Issue by amarildolucas** [semaphoreci-demos/semaphore-demo-ios-swift-xcode#7]
I think that it has some inconsistencies in the docs vs the demo project. 

In the demo project:
```
# Add the key for the match certificate repository to ssh
# See https://docs.semaphoreci.com/article/109-using-private-dependencies
- chmod 0600 ~/.ssh/*
- ssh-add ~/.ssh/match-repository-private-key
```

In the documentation when looking for help: https://docs.semaphoreci.com/article/109-using-private-dependencies
```
- chmod 0600 ~/.keys/*
# Add the key to the ssh agent:
- ssh-add ~/.keys/*
```

It can be confused for beginners if they create their secrets with `sem create secret private-repo --file id_rsa_semaphoreci:/home/semaphore/.keys/private-repo` than try to follow with the demo project configuration.

**Comment by markoa** [comment]
In general links to docs in YML are meant to be read for additional information on how something works on Semaphore.

I think it's strange that the docs article is referring to `~/.keys` directory when on both Linux and Mac you typically use `~/.ssh`. I propose changing the docs page to have `~/.ssh`, what do you think?

**Comment by amarildolucas** [comment]
I agree with you @markoa. `~/.ssh` it's probably more familiar for beginner developers.

**Comment by markoa** [comment]
Updated the docs page.
